### ISSUE TITLE
Upload changeset timeout

### ISSUE THREAD

**Issue by regan-sarwas** [nationalparkservice/places-api#14]
Currently, the upload/<changeset_id> api times out and does not return the diffresult for large datasets.  This causes a problem with the arc2places workflow.   I would like to develop two new api calls.  1) very similar to existing upload/<changeset_id>, however it would return before doing any significant processing (maybe just check for valid xml)  It would upload **and close** the changeset asynchronously.  2) A second api call  that takes the changeset id, and returns an error if the changeset doesn't fully exist yet, or if the processing was done, a replacement for the diffresult that would have been returned from the original upload.  Since the temporary (negative) element ids are now long gone, I would prefer a result that is specific to the arc2places workflow.  One that would create a table (csv or json is preferable to XML) that provides the places id with the elements in the changeset that have a 'nps:source_system_key_value' tag.  The GET changeset call could probably be used to check if the processing is done, but I would not need it.

I know you are busy with the move, so I am happy to code this up as long as you think it is something you are willing to implement.

**Comment by jimmyrocks** [comment]
It looks like @regan-sarwas' change might fix this?
